name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Instalar dependências (Pandoc, Make, LaTeX, KaTeX)
        run: sudo apt-get install -y pandoc make texlive-xetex texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra

      - name: Executar Makefile para gerar manual.html
        run: |
          cd manual
          make dist

      - name: Listar arquivos gerados
        run: |
          echo "Arquivos em manual/build:"
          ls -l manual/build/

      - name: Verificar se manual.html foi gerado
        run: |
          if [ ! -f manual/build/manual.html ]; then
            echo "Erro: manual.html não foi gerado."
            exit 1
          fi

      - name: Criar a branch gh-pages se não existir
        run: |
          git fetch origin
          if ! git show-ref --verify --quiet refs/remotes/origin/gh-pages; then
            git checkout --orphan gh-pages
          else
            git checkout gh-pages
          fi

      - name: Copiar arquivos gerados para a pasta correta
        run: |
          rm -rf public || true
          mkdir -p public
          cp -r manual/build/* public/

      - name: Deploy para GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
